Credentials
Eliheakins/Stack-Overflow-Clone pull request #76
Opened 2024-12-12 17:44 UTC by JacobKrehbiel03

This is a basic implementation of the credential system. I couldn't figure out how to link the credential issue to the pull request, so apologies for that not being attached

Some of the views aren't updated yet, as I would like to make another partial for posts, then use that, instead of changing all places where posts appear. I will work on that today.

The cucumber step features/tests aren't complete as some of the placements of the buttons are up in the air for me right now, so I wanted a bit of feedback if the user profile page seems the correct place, so testing is limited to a couple rspec tests (and just following it in the server, tracking if what should happen does)

Additionally, no javascript is used right now for the table, but I will try to add it once we are more feature complete in other areas.

2024-12-12 21:14 UTC, Eliheakins requested changes
When I log in as the seeded user (username: user, password: password) and navigate to the user profile and hit Send credentials I get
No view template for interactive request
UserCredsController#new is missing a template for request formats: text/html
NOTE: Rails usually expects a controller action to render a view template with the same name.

For example, a UserCredsController#new action defined in app/controllers/user_creds_controller.rb should have a corresponding view template in a file named app/views/user_creds/new.html.erb.

However, if this controller is an API endpoint responding with 204 (No Content), which does not require a view template because it doesn't serve an HTML response, then this error will occur when trying to access it with a browser. In this particular scenario, you can ignore this error.

You can find more about view template rendering conventions in the [Rails Guides on Layouts and Rendering in Rails](https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-by-default-convention-over-configuration-in-action).

2024-12-12 21:15 UTC, Eliheakins commented
Rest of it looks great, though one minor styling thing I noticed. Maybe it shouldn't say Instructor Response for posts, only replies

2024-12-12 23:14 UTC, JacobKrehbiel03 commented
Oh oops, I think I forgot to git add one last time.

2024-12-13 02:56 UTC, Eliheakins approved these changes

2024-12-13 02:56 UTC, merged